### ISSUE TITLE
No realiza los token

### ISSUE THREAD

**Issue by luishdez87** [NeriCodec/nativescript-open-pay#1]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
Hola @NeriCodec quería agradecerte por el plugin y preguntarte si sabes con cuál versión de nativescript es la última versión estable, debido a que estoy usando la última y no realiza la tokenizacion, si me pudieras ayudar estaría muy agradecido. 
Saludos.

**Comment by nericode** [comment]
Hola @luishdez87  necesitaría ver tu implementación o un ejemplo porque yo lo estoy usando en la ultima versión de Nativescript perfectamente.

**Comment by nericode** [comment]
Cerrado por inactividad. #1
